### PR TITLE
Require Ollama LLM provider dependency

### LINKED ISSUE #458: langchain/llm/ollama.rb NameError: uninitialized constant Langchain::LLM::Ollama::Faraday
- In the Ollama client, Faraday is assumed to be autoloaded, which is not likely the case when outside of Rails
- Faraday also does not show up in the gem dependencies, and therefor must be installed separately, even though the constant is directly referenced in [this code](https://github.com/andreibondarev/langchainrb/blob/005c39b38b8d15bd0d0ed40cb819fb61d749d24d/lib/langchain/llm/ollama.rb#L217).

I see that Faraday appears in the Gemfile for the project, so tests pass when doing development, but do not work through gem distribution. Additionally, `require 'faraday'` is in the test file, but should also be in the client file to play nicely without Rails.

```
▶ gem install pry langchainrb
Fetching pry-0.14.2.gem
Successfully installed pry-0.14.2
Parsing documentation for pry-0.14.2
Installing ri documentation for pry-0.14.2
Done installing documentation for pry after 0 seconds
Fetching langchainrb-0.9.0.gem
Successfully installed langchainrb-0.9.0
Parsing documentation for langchainrb-0.9.0
Installing ri documentation for langchainrb-0.9.0
Done installing documentation for langchainrb after 0 seconds
2 gems installed

~
▶ pry
[1] pry(main)> require 'langchainrb'
=> true
[2] pry(main)> llm = Langchain::LLM::Ollama.new(url: 'http://localhost:11434')
=> #<Langchain::LLM::Ollama:0x000000011fb59918 @url="http://localhost:11434">
[3] pry(main)> llm.complete(prompt: "Hello world", model: "mistral")
NameError: uninitialized constant Langchain::LLM::Ollama::Faraday
from /Users/ttilberg/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/langchainrb-0.9.0/lib/langchain/llm/ollama.rb:84:in `client'
[4] pry(main)> require 'faraday'
LoadError: cannot load such file -- faraday
from <internal:/Users/ttilberg/.asdf/installs/ruby/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:127:in `require'
```

### PR DESCRIPTION
**Pull request by ttilberg**
This change establishes Faraday as a required dependency for the Ollama LLM provider. Additionally, it starts to add documentation in the Readme that each of the LLMs may have their own dependencies that are not included by default.

Fixes #458

### CODE REVIEW

File: lib/langchain/llm/ollama.rb [hunk 1]
```diff
@@ -22,6 +22,7 @@ class Ollama < Base
     # @param default_options [Hash] The default options to use
     #
     def initialize(url:, default_options: {})
+      depends_on 'faraday'
```
Comment (andreibondarev) [inline lib/langchain/llm/ollama.rb:25]: Double quotes, otherwise the linter complains.

**Review by andreibondarev — APPROVED** [review]

**Comment by andreibondarev** [comment]
Thank you for the fix. Just the linter error!

**Comment by ttilberg** [comment]
Hi @andreibondarev,

After taking my initial stab at just `require`ing Faraday, I started to notice other infrastructure in place to help load required Gems using Langchain::DependencyHelper. I've mimicked how other LLM providers appear to be handling dependency resolution. However, I'm not sure I have this configured correctly:

If I comment out `require 'faraday'` in the spec, I'd expect the spec that references the Faraday constant to possibly fail if it hasn't been required yet, but I also get

```
  2) Langchain::LLM::Ollama#chat returns a chat completion
     Failure/Error:
       @client ||= Faraday.new(url: url) do |conn|
         conn.request :json
         conn.response :json
         conn.response :raise_error
       end

     NameError:
       uninitialized constant Langchain::LLM::Ollama::Faraday

             @client ||= Faraday.new(url: url) do |conn|
                         ^^^^^^^
     # ./lib/langchain/llm/ollama.rb:220:in `client'
     # ./spec/langchain/llm/ollama_spec.rb:43:in `block (3 levels) in <top (required)>'

```

I would have expected this to be resolved by the `depends_on` helper, do you agree?

File: lib/langchain/llm/ollama.rb (hunk 1 above)
Comment (ttilberg) [reply lib/langchain/llm/ollama.rb]: Hah, I caught that and re-force pushed right afterwards. You were too quick (I was too slow!) ;)

**Comment by andreibondarev** [comment]
@ttilberg I suspect that you may need to add `faraday` to the gemspec file. 

Also -- does referencing the top-level namespace fix the issue?
```ruby
@client ||= ::Faraday.new
```

**Comment by ttilberg** [comment]
@andreibondarev I've added Faraday to the Gemspec. I believe this brings parity to the Ollama provider now.

**Comment by andreibondarev** [comment]
@ttilberg Let's ship it! 🚀 🚢
